# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  VENV_DIR: 'venv'

stages:
  - stage: BuildAndTest
    jobs:
      - job: BuildAndTestJob
        steps:
          - checkout: self

          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
              addToPath: true

          - script: |
              echo "MY_VAR is: $(MY_VAR)"  # Print the MY_VAR value
              python -m venv $(VENV_DIR)
              ./$(VENV_DIR)/bin/pip install --upgrade pip
              ./$(VENV_DIR)/bin/pip install -r requirements.txt
              ./$(VENV_DIR)/bin/python -m pytest test_hello_world.py -v
            displayName: 'Set up venv, install deps, run tests'

  - stage: RunApp
    dependsOn: BuildAndTest
    jobs:
      - job: RunAppJob
        steps:
          - checkout: self

          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
              addToPath: true

          - script: |
              echo "MY_VAR is: $(MY_VAR)"  # Print the MY_VAR value
              python -m venv $(VENV_DIR)
              ./$(VENV_DIR)/bin/pip install -r requirements.txt
              ./$(VENV_DIR)/bin/python hello_world.py
            displayName: 'Run hello_world.py'
